[project]
name = "documentation-generator"
version = "0.0.1"
dependencies = [
    "python-dotenv",
    "requests",
    "pydantic",
    "cryptography",
    "langchain",
    "langchain-community",
    "langchain-google-genai",
]

[project.optional-dependencies]
local = [
    "build"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
