[project]
name = "documentation-generator"
version = "0.0.1"
dependencies = [
    "python-dotenv",
    "requests",
    "pydantic",
    "cryptography",
    "langchain",
    "langchain-community",
    "langchain-google-genai",
]

[project.optional-dependencies]
local = [
    "build",
    "pre-commit",
]

[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
